### User sing up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
"name": "Likan Shrestha",
"company": "Company Name",
"address": "Some address Sydney",
"phone":999,
"email":"likan.stha@gmail.com",
"password":"12345678"
}

### User sing in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json 

{
    "email": "likan.stha@gmail.com",
    "password":"12345678910"
       
}


### User a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpa2FuQGdtYWlsLmNvbSIsImlhdCI6MTY1NzM0NzI1MCwiZXhwIjoxNjU3MzQ3MzEwfQ.-Hw_IauL_yyyyLvo2xhVxUqxLxRZfzLZAlnRIUajNt0

### Token router
GET http://localhost:3001/v1/tokens
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpa2FuQGdtYWlsLmNvbSIsImlhdCI6MTY1NzM0NzE3MiwiZXhwIjoxNjU5OTM5MTcyfQ.qbHrInqpVv_XNXpgrRx08Cx5mG_VNqlEr6AGdl49wlI



### Password reset endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"likan.stha2@gmail.com"
}

### Update newvPassword endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"likan.stha@gmail.com",
    "pin":7501857,
    "newPassword":"12345678910"
}

