### User sing up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
"name": "Likan Shrestha",
"company": "Company Name",
"address": "Some address Sydney",
"phone":999,
"email":"likan.stha@gmail.com",
"password":"12345678"
}

### User sing in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json 

{
    "email": "likan.stha@gmail.com",
    "password":"12345678910"
       
}


### User a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpa2FuLnN0aGFAZ21haWwuY29tIiwiaWF0IjoxNjU3NDQxNjQwLCJleHAiOjE2NTc0NDI1NDB9.dI2W8Yjy60xfKgUTLGigrQ1ZnhF4iFvau2hVuuhkJ_I

### Token router new token generator
GET http://localhost:3001/v1/tokens
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpa2FuQGdtYWlsLmNvbSIsImlhdCI6MTY1NzM0NzE3MiwiZXhwIjoxNjU5OTM5MTcyfQ.qbHrInqpVv_XNXpgrRx08Cx5mG_VNqlEr6AGdl49wlI



### Password reset endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"likan.stha@gmail.com"
}

### Update new Password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"likan.stha@gmail.com",
    "pin":348863,
    "newPassword":"0"
}

### User Logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpa2FuLnN0aGFAZ21haWwuY29tIiwiaWF0IjoxNjU3NDQxNjQwLCJleHAiOjE2NTc0NDI1NDB9.dI2W8Yjy60xfKgUTLGigrQ1ZnhF4iFvau2hVuuhkJ_I




 
### Open new ticket
POST http://localhost:3001/v1/ticket
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpa2FuLnN0aGFAZ21haWwuY29tIiwiaWF0IjoxNjU3NDQ0Njc2LCJleHAiOjE2NTc0NDU1NzZ9.79gXsRfBLIvSKGYQgPIHXx_DvamUDB52W7w_pUG3w4g

{
 "subject": "Form Isue",
  "sender": "Likan",
  "message": "1 Contact form not working. please fix it as soon as possible" 
}

###Get all the tickets
GET http://localhost:3001/v1/ticket
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpa2FuLnN0aGFAZ21haWwuY29tIiwiaWF0IjoxNjU3NDQ0Njc2LCJleHAiOjE2NTc0NDU1NzZ9.79gXsRfBLIvSKGYQgPIHXx_DvamUDB52W7w_pUG3w4g


### Get single ticket
GET http://localhost:3001/v1/ticket/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpa2FuLnN0aGFAZ21haWwuY29tIiwiaWF0IjoxNjU3NDQ2MzQ1LCJleHAiOjE2NTc0NDcyNDV9.yuekR0M7V4aMjdqFXL4jgmmucCNWMxzLnIwjQIonNGA

### Reply message to the ticket
PUT http://localhost:3001/v1/ticket/62ca9b729179be28cc3ea1b1
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA5ODkxOTg0LCJleHAiOjE2MDk5NzgzODR9.7cUfpK_RF68a-xfxVXuet4PWVqwToUPyDXpupFlCQNI
Content-Type: application/json 

{ 
    "message": "this is the 222 reply", 
    "sender": "Sarita " 
}